d-php-letsencrypt:
  ports:
  - 65500:80/tcp
  - 65502:22/tcp
  - 65503:443/tcp
  environment:
    DWL_LOCAL: en_US.UTF-8
    DWL_USER_ID: '1000'
    DWL_USER_PASSWD: secret
    DWL_LOCAL_LANG: en_US:en
    DWL_USER_NAME: username
    DWL_SSH_ACCESS: 'true'
    DWL_SHIELD_HTTP: 'false'
    DWL_SSLKEY_C: EU
    DWL_SSLKEY_ST: France
    DWL_SSLKEY_L: Vannes
    DWL_SSLKEY_O: davask web limited - docker container
    DWL_SSLKEY_CN: davaskweblimited.com
    DWL_CERTBOT_EMAIL: docker@davaskweblimited.com
    DWL_CERTBOT_DEBUG: 'false'
  image: davask/d-wordpress:4.4.2-p5.6-a2.4-u14.04
  hostname: localhost
  net: bridge
  volumes:
  - /home/dwl/docker-images/app/d-wordpress/build/etc/letsencrypt:/etc/letsencrypt
  - /home/dwl/docker-images/app/d-wordpress/build/etc/apache2/ssl:/etc/apache2/ssl
  - /home/dwl/docker-images/app/d-wordpress/volumes/proxy/log/localhost/apache2:/var/log/apache2
  - /home/dwl/docker-images/app/d-wordpress/volumes/home/username/http/app/sites-available:/etc/apache2/sites-available
  - /home/dwl/docker-images/app/d-wordpress/volumes/home/username/files:/home/username/files
  working_dir: /var/www/html

